version: '3.8'

networks:
  mars_network:
    driver: bridge

services:
  converter:
    build: ./services/converter
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - audio_data:/app/uploads
      - audio_data:/app/outputs
    environment:
      - MONGODB_URI=mongodb://converter-db:27017/
      - MONGODB_DB=converter_db
      - REDIS_URL=redis://redis:6379/0
    networks:
      - mars_network
    depends_on:
      - converter-db
      - redis

  converter-worker:
    build: ./services/converter
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - audio_data:/app/uploads
      - audio_data:/app/outputs
    environment:
      - MONGODB_URI=mongodb://converter-db:27017/
      - MONGODB_DB=converter_db
      - REDIS_URL=redis://redis:6379/0
    networks:
      - mars_network
    depends_on:
      - converter-db
      - redis

  transcription:
    build: ./services/transcription
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    volumes:
      - audio_data:/app/uploads
    environment:
      - MONGODB_URI=mongodb://transcription-db:27017/
      - MONGODB_DB=transcription_db
      - REDIS_URL=redis://redis:6379/0
      - CONVERTER_SERVICE_URL=http://converter:8000
    networks:
      - mars_network
    depends_on:
      - transcription-db
      - redis
      - converter

  transcription-worker:
    build: ./services/transcription
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - audio_data:/app/uploads
      - whisper_cache:/app/whisper_cache
    environment:
      - MONGODB_URI=mongodb://transcription-db:27017/
      - MONGODB_DB=transcription_db
      - REDIS_URL=redis://redis:6379/0
    networks:
      - mars_network
    depends_on:
      - transcription-db
      - redis

  summarization:
    build: ./services/summarization
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8002:8000"
    environment:
      - MONGODB_URI=mongodb://summarization-db:27017/
      - MONGODB_DB=summarization_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRANSCRIPTION_SERVICE_URL=http://transcription:8000
    networks:
      - mars_network
    depends_on:
      - summarization-db
      - redis

  summarization-worker:
    build: ./services/summarization
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - MONGODB_URI=mongodb://summarization-db:27017/
      - MONGODB_DB=summarization_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - mars_network
    depends_on:
      - summarization-db
      - redis

  converter-db:
    image: mongo:latest
    volumes:
      - converter_db:/data/db
    networks:
      - mars_network

  transcription-db:
    image: mongo:latest
    volumes:
      - transcription_db:/data/db
    networks:
      - mars_network

  summarization-db:
    image: mongo:latest
    volumes:
      - summarization_db:/data/db
    networks:
      - mars_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mars_network

volumes:
  audio_data:
  whisper_cache:
  converter_db:
  transcription_db:
  summarization_db: