networks:
  mars_network:
    driver: bridge

services:
  converter:
    build: ./services/converter
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - audio_uploads:/app/uploads     # 원본 파일 저장
      - audio_converted:/app/outputs   # 변환된 WAV 파일 저장
    environment:
      - MONGODB_URI=mongodb://converter-db:27017/
      - MONGODB_DB=converter_db
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
    networks:
      - mars_network
    depends_on:
      - converter-db
      - redis

  converter-worker:
    build: ./services/converter
    command: celery -A app.tasks worker --loglevel=debug -Q converter  # info에서 debug로 변경
    volumes:
      - audio_uploads:/app/uploads     # 원본 파일 저장
      - audio_converted:/app/outputs   # 변환된 WAV 파일 저장
    environment:
      - MONGODB_URI=mongodb://converter-db:27017/
      - MONGODB_DB=converter_db
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
    networks:
      - mars_network
    depends_on:
      - converter-db
      - redis

  transcription:
    build: ./services/transcription
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    volumes:
      - audio_converted:/app/uploads   # 변환된 WAV 파일 접근
      - transcription_outputs:/app/outputs  # 텍스트 파일 저장
    environment:
      - MONGODB_URI=mongodb://transcription-db:27017/
      - MONGODB_DB=transcription_db
      - REDIS_URL=redis://redis:6379/0
      - CONVERTER_SERVICE_URL=http://converter:8000
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
    networks:
      - mars_network
    depends_on:
      - transcription-db
      - redis
      - converter

  transcription-worker:
    build: ./services/transcription
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - audio_converted:/app/uploads   # 변환된 WAV 파일 접근
      - transcription_outputs:/app/outputs  # 텍스트 파일 저장
      - ./whisper_cache:/app/whisper_cache
    environment:
      - MONGODB_URI=mongodb://transcription-db:27017/
      - MONGODB_DB=transcription_db
      - REDIS_URL=redis://redis:6379/0
    networks:
      - mars_network
    depends_on:
      - transcription-db
      - redis

  summarization:
    build: ./services/summarization
    volumes:
      - transcription_outputs:/app/uploads  # 텍스트 파일 접근
      - summarization_outputs:/app/outputs  # 요약 파일 저장
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8002:8000"
    environment:
      - MONGODB_URI=mongodb://summarization-db:27017/
      - MONGODB_DB=summarization_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRANSCRIPTION_SERVICE_URL=http://transcription:8000
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
    networks:
      - mars_network
    depends_on:
      - summarization-db
      - redis

  summarization-worker:
    build: ./services/summarization
    volumes:
      - transcription_outputs:/app/uploads  # 텍스트 파일 접근
      - summarization_outputs:/app/outputs  # 요약 파일 저장
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - MONGODB_URI=mongodb://summarization-db:27017/
      - MONGODB_DB=summarization_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
    networks:
      - mars_network
    depends_on:
      - summarization-db
      - redis

  converter-db:
    image: mongo:latest
    volumes:
      - ./converter_db:/data/db
    networks:
      - mars_network

  transcription-db:
    image: mongo:latest
    volumes:
      - ./transcription_db:/data/db
    networks:
      - mars_network

  summarization-db:
    image: mongo:latest
    volumes:
      - ./summarization_db:/data/db
    networks:
      - mars_network

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - mars_network

  api_gateway:
    build: ./services/api_gateway
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CONVERTER_SERVICE_URL=http://converter:8000
      - TRANSCRIPTION_SERVICE_URL=http://transcription:8000
      - SUMMARIZATION_SERVICE_URL=http://summarization:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - mars_network
    depends_on:
      - redis
      - converter
      - transcription
      - summarization

volumes:
  whisper_cache:
  converter_db:
  transcription_db:
  summarization_db:
  audio_uploads:           # 원본 오디오 파일
  audio_converted:         # 변환된 WAV 파일
  transcription_outputs:   # 텍스트 변환 결과
  summarization_outputs:   # 요약 결과