services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - converter
    networks:
      - my-network

  converter:
    build: ./converter
    ports:
      - "5001:5000"
    volumes:
      - ./converter:/app
    command: python app.py
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
